import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/navbar";
import Footer from "@/components/ui/footer";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.variable} antialiased`}>
        <div className="fixed bg-black top-0 w-full max-w-600 w-full m-auto p-4 z-10">
          <Navbar />
        </div>
        <div className="mt-20">{children}</div>
        <div className="bottom-0 h-30 w-full max-w-600 w-full m-auto p-4">
          <Footer />
        </div>
      </body>
    </html>
  );
}
